# Site settings
title: Wahyu Rahmaniar 
#twitter_username: wahyurahmaniar
name: Wahyu Rahmaniar

# Build settings
#markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://technologination.blogspot.com/
 - title: GitHub
   url: https://github.com/wahyurahmaniar  
 - title: LinkedIn
   url: https://www.linkedin.com/in/wahyu-rahmaniar-22041987/
 - title: Facebook
   url: https://www.facebook.com/wahyu.rahmaniar
 - title: Twitter
   url: https://twitter.com/WahyuRahmaniar
 - title: Google Scholar
   url: https://scholar.google.com/citations?user=V81MER8AAAAJ&hl=id
 - title: Scopus
   url: https://www.scopus.com/authid/detail.uri?authorId=56982984800
 - title: ResearchGate
   url: https://www.researchgate.net/profile/Wahyu-Rahmaniar

#Any buzzword skills you want to include
skills:
 - C/C++
 - C#
 - Java
 - MATLAB
 - Python
 - PyTorch
 - Tensorflow
 - Visual Basic

skills2:
 - Arduino
 - AVR Studio
 - Bascom AVR
 - Eagle PCB
 - Microcontroller
 - NVIDIA Jetson
 - PLC
 - Protel PCB
 - Raspberry Pi
 - Solidworks
 - Verilog

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: Previous Research

#Work experience is required
#roles:
# - title: CTO
#   start: 2017
#   end: Ongoing
#   employer: Basement Crowd
#   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.

#Education is required
education:
 - level: Doctor of Philosophy (P.hD.)
   date: 2020
   dept: Electrical Engineering
   subject: (Computer Vision and Artificial Intelligence)
   school: National Central University
 - level: (M.Sc. fastrack to P.hD.)
   date: 2014
   dept: Electrical Engineering
   subject: (Robotics and Computer Vision)
   school: National Central University
 - level: Bachelor of Science / Sarjana Sains (S.Si.)
   date: 2009
   dept: Electronics and Instrumentation
   subject: (Robotics and Control)
   school: Universitas Gadjah Mada

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   talks:
    - title: Menggapai Mimpi di Kancah Internasional
      host: Universitas Internasional Semen Indonesia (UISI)
      date: July 4, 2020
   talks2:
    - title: Artificial Intelligence Applications in Real-Life
      host: Sekolah Tinggi Teknologi Bandung (STTB)
      date: July 10, 2021
   talks3:
    - title: When Remote Sensing Meets Artificial Intelligence 
      host: Universitas Negeri Makasar (UNM)
      date: December 4, 2021

#List of interesting Github repo/projects to include - optional
#github:
# - wahyurahmaniar/wahyurahmaniar.github.io

#Stackoverflow flair is optional
stackoverflow: Resume
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  <p style="font-size:15px;">
  Currently I'm a Postdoctoral Researcher at National Taipei University of Technology, Taiwan. I received the B.S. degree in Electronics and Instrumentation from Universitas Gadjah Mada, Yogyakarta, Indonesia, in 2009 and Ph.D. degree in Electrical Engineering from National Central University, Taiwan, in 2020. 
  My research interests are in the areas of robotics, computer vision, image processing, and artificial intelligence (AI). <br/><br/>
  
  The research I conducted in the field of computer vision and image processing, including AI, I used C++ or Python programming on Windows or Linux operating systems. Overall, I have at least 10 years experience in programming. And for the AI field, I have studied it since I took a Ph.D. degree until now for about 7 years.
  For intelligent systems, I focus more on developing algorithms or frameworks that can run systems in the real-time in the actual environment. Besides, I also understand well enough the theory and mathematics for these systems, including machine learning and deep learning. One of my interests in AI research is that I want to create my own network or method. 
  I have also been a reviewer in several journals, such as Circuit World, Sensor Review, Journal of Robotics and Control, Journal of Electronic Imaging, Sensors (MDPI), BDCC (MDPI), and Scientific Reports (Nature). <br/><br/>
  </p>
  <p style="color:blue "align="right">~ayuchan~</p>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <p style="font-size:14px;"><strong>Year</strong>: November 2021 - now <br/>
   <strong>Company</strong>: National Taipei University of Technology, Taiwan<br/>
   <strong>Position</strong>: Postdoctoral Researcher <br/>
   <strong>Subject</strong>: Programming, computer vision, image processing, artificial intelligence <br/>
   </p>

   <p style="font-size:14px;"><strong>Year</strong>: December 2018 - October 2021 <br/>
   <strong>Company</strong>: Issa Technology, Taoyuan, Taiwan <br/>
   <strong>Position</strong>: Software Engineer <br/>
   <strong>Subject</strong>: Programming, computer vision, image processing, artificial intelligence <br/>
   </p>

   <p style="font-size:14px;"><strong>Year</strong>: October 2017 – January 2018 <br/>
   <strong>Company</strong>: Shibaura Institute of Technology, Japan <br/>
   <strong>Position</strong>: Exchange Student <br/>
   <strong>Subject</strong>: Automatic localization of UAV in an unknown environment <br/>
   </p>
 
   <p style="font-size:14px;"><strong>Year</strong>: June 2017 - August 2017 <br/>
   <strong>Company</strong>: Ubiik Inc, Hsinchu, Taiwan <br/>
   <strong>Position</strong>: Internship, Software Engineer <br/>
   <strong>Subject</strong>: Program and embedded system for Smart Power Meter <br/>
   </p>
   
   <p style="font-size:14px;"><strong>Year</strong>: May 2009 - August 2013 <br/>
   <strong>Position</strong>: Freelancer <br/>
   <strong>Subject</strong>: Programming and electronics<br/>
   </p>
   
   <p style="font-size:14px;"><strong>Year</strong>: November 2010 - October 2011 <br/>
   <strong>Company</strong>: Institut Teknologi Sepuluh Nopember, Surabaya, Indonesia <br/>
   <strong>Position</strong>: Research Assistant <br/>
   <strong>Subject</strong>: Programming and electronics <br/>
   </p>
 
   <p style="font-size:14px;"><strong>Year</strong>: May 2010 – October 2010 <br/>
   <strong>Company</strong>: Universitas Indonesia, Depok, Indonesia <br/>
   <strong>Position</strong>: Research Assistant <br/>
   <strong>Subject</strong>: Programming and electronics <br/>
   </p>
  
   <p style="font-size:14px;"><strong>Year</strong>: August 2009 - January 2010 <br/>
   <strong>Company</strong>: Universitas Gadjah Mada, Yogyakarta, Indonesia <br/>
   <strong>Position</strong>: Laboratory Assistant <br/>
   <strong>Subject</strong>: Teaching class and experiment in electronics and programming <br/>
   </p>
